version: "3.4"

services:
  itau.pagebroker.dev:
    container_name: itau.pagebroker.dev
    build:
      context: ./
      dockerfile: Dockerfile
    image: itau.pagebroker.dev
    volumes:
      - ./:/app
    networks:
      - bubble

networks:
  bubble:
    external: true
